<?php

return [
    'web' => [
        'index' => [
            'pagetitle' => 'Home',
            'template' => 1,
            'hidemenu' => false,
        ],
        'system' => [
            'pagetitle' => 'System',
            'template' => 1,
            'hidemenu' => true,
            'published' => false,
            'checked' => 1,
            'blocked' => 1,
            'cacheable' => 0,
            'parent' => 0,
            'richtext' => 0,
            'searchable' => 0,
            'content' => '',
            'resources' => [
                'service' => [
                    'content' => '',
                    'pagetitle' => 'Service',
                    'hidemenu' => false,
                    'published' => false,
                    'description' => 'контенер для страниц 403,404,503,sitemap,robots.txt',
                    'resources' => [
                        '404' => [
                            'pagetitle' => 'Страница не найдена',
                            'template' => 1,
                            'hidemenu' => true,
                            'uri' => '404',
                            'uri_override' => true,
                        ],
                        '403' => [
                            'pagetitle' => '403',
                            'template' => 1,
                            'hidemenu' => true,
                            'uri' => '403',
                            'uri_override' => true,
                        ],
                        '503' => [
                            'pagetitle' => '503',
                            'template' => 1,
                            'hidemenu' => true,
                            'uri' => '503',
                            'uri_override' => true,
                        ],
                    ],

                ],
                'search' => [
                    'pagetitle' => 'Поиск',
                    'checked' => 0,
                    'desc' => 'страница для поиска по сайту',
                    'template' => 1,
                    'published' => 1,
                    'hidemenu' => 1,
                    'alias' => 'search',
                    'richtext' => 0,
                    'searchable' => 0,
                    'uri_override' => 1,
                    'uri' => 'search',
                    'content' => ''
                ],
                'sitemap.xml' => [
                    'pagetitle' => 'Sitemap',
                    'template' => 0,
                    'hidemenu' => true,
                    'uri' => 'sitemap.xml',
                    'uri_override' => true,
                ],
                'robots.txt' => [
                    'pagetitle' => 'Robots',
                    'checked' => 1,
                    'description' => 'тоже самое что и robots.txt только ресурсом',
                    'template' => 0,
                    'published' => 1,
                    'hidemenu' => 1,
                    'alias' => 'robots',
                    'content_type' => 3,
                    'richtext' => 0,
                    'searchable' => 0,
                    'uri_override' => 1,
                    'uri' => 'robots.txt',
                ],
                'cart' => [
                    'pagetitle' => 'Корзина',
                    'checked' => 0,
                    'desc' => 'страница корзины со снипетами: [[!msCart?]][[!msOrder?]]',
                    'template' => 1,
                    'published' => 1,
                    'hidemenu' => 1,
                    'alias' => 'cart',
                    'richtext' => 0,
                    'searchable' => 0,
                    'uri_override' => 1,
                    'uri' => 'cart',
                ]
            ],
        ],
        'contacts' => array(
            'pagetitle' => 'Контакты',
            'checked' => 0,
            'desc' => '',
            'template' => 1,
            'published' => 1,
            'hidemenu' => 0,
            'alias' => 'contacts',
            'parent' => 0,
            'richtext' => 0,
            'searchable' => 1,
            'uri_override' => 1,
            'uri' => 'contacts.html',
        )
    ],
];